# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22f2f9c12d2d5978dbde08ffcc9cea9e69fe9b3e43671796004075352377b388a7bdcf3279fc9ed1ad2a06e135e8b89dfd1f4efd6f39283dd089dc409623f67b

test:
  secret_key_base: 51fe30eef7275c9daf6e123dc25eff5344b2dbaa68322bfb4ac3782f019c62131eb5bc80d1a28638c394286f2881daf33d50f948398c0d965749d9e7661a9c57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
